"""baseline schema

Revision ID: 9ac5d3b0b871
Revises: 
Create Date: 2026-07-22 22:58:05.222842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ac5d3b0b871'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('owner_ad_group', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_scan_id', sa.String(), nullable=True),
    # fk_apps_current_scan_id is added after 'scans' exists — see below.
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by', sa.String(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_app_id'), 'scans', ['app_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    # apps.current_scan_id -> scans.id closes a cycle with scans.app_id -> apps.id, so
    # it can only be added once both tables exist. The model marks it use_alter=True,
    # which create_all() honours by emitting a separate ALTER — but autogenerate renders
    # it inline into create_table('apps'), where SQLAlchemy silently omits it and the
    # constraint is never created at all. Hand-lifted here on purpose; do not fold it
    # back into create_table.
    op.create_foreign_key(
        'fk_apps_current_scan_id',
        'apps',
        'scans',
        ['current_scan_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('auth_method', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_on_page', sa.String(), nullable=False),
    sa.Column('headers_snippet', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_table('scan_events',
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    # BigInteger: ts is epoch milliseconds, which overflows int32.
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    # The composite PK is what enforces one event per (scan, seq) — EventBus relies on
    # it to reject a duplicate seq allocated by a concurrent emit.
    sa.PrimaryKeyConstraint('scan_id', 'seq')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', name='uq_submissions_scan_id')
    )
    op.create_index(op.f('ix_submissions_scan_id'), 'submissions', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Break the apps <-> scans cycle first, or dropping 'scans' fails.
    op.drop_constraint('fk_apps_current_scan_id', 'apps', type_='foreignkey')
    op.drop_index(op.f('ix_submissions_scan_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_app_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('apps')
    # ### end Alembic commands ###
