apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fastapi-scraper
  labels:
    app: fastapi-scraper
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: fastapi-scraper:latest
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
